# Numpy

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6])

In [3]:
a

array([1, 2, 3, 4, 5, 6])

In [5]:
list1=[1,2,3],[4,5,6]
print(type(list1))
arr=np.array(list1)
arr

<class 'tuple'>


array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Zeros and Ones

In [8]:
np.zeros(2)

array([0., 0.])

In [10]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [11]:
np.zeros((3,4,5), dtype=int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [9]:
np.ones(2)

array([1., 1.])

In [12]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [43]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#Buit In Methods

In [15]:
np.empty(2)

array([1., 1.])

In [16]:
np.empty(2,dtype=int)

array([4607182418800017408, 4607182418800017408])

In [17]:
np.arange(4)

array([0, 1, 2, 3])

In [18]:
k=np.arange(0,4)
l=np.arange(0,10,2)
print(k,l)

[0 1 2 3] [0 2 4 6 8]


In [21]:
a = np.arange(0,15)
v=a.reshape(5,3)
v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [22]:
b = np.arange(6)
print(b)

[0 1 2 3 4 5]


In [24]:
c = b.reshape(3, 2)
print(c)

[[0 1]
 [2 3]
 [4 5]]


In [25]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [26]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
np.linspace(0,10,20, retstep=True)

(array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
         2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
         5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
         7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ]),
 0.5263157894736842)

In [30]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [35]:
x=np.sort(arr)

In [32]:
b = np.array([9, 10, 11, 12])

In [37]:
np.concatenate((x,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [39]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
a.ndim

2

In [41]:
a.size

12

In [42]:
a.shape

(3, 4)

#Random

In [44]:
# rand
from numpy import random
random.rand(10)

array([0.82447208, 0.71743836, 0.29242238, 0.54750919, 0.48425446,
       0.37836131, 0.27075338, 0.06887831, 0.96845644, 0.91543699])

In [47]:
np.random.seed(2)
np.random.rand(10)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ,
       0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728])

In [49]:
np.random.rand(10)

array([0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987,
       0.78533515, 0.85397529, 0.49423684, 0.84656149, 0.07964548])

In [52]:
# randn
np.random.seed(0)
y = np.random.randn(10)
y

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [53]:
# randint
import warnings
warnings.filterwarnings('ignore')

In [54]:
np.random.randint(2, 100)

41

In [55]:
np.random.randint(1,100,10)

array([88, 47, 89, 82, 38, 26, 78, 73, 10, 21])

In [57]:
np.random.randint(1,100,size=(3,4))

array([[95, 68, 83, 47],
       [21, 82, 51, 28],
       [15, 42, 59, 66]])

In [58]:
np.random.seed(1)
ranarr = np.random.randint(0,100,10) # integers
ranarr

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1])

In [59]:
ranarr.max()

79

In [60]:
ranarr.min()

1

In [61]:
ranarr.argmin()

9

# Array Operations

In [62]:
a=np.array([1,2,3,5])
b=np.array([1])
a+b

array([2, 3, 4, 6])

In [63]:
x = np.array([[1, 2], [3, 4], [5,6], [7,8]])
y = np.array([[1, 2]])
x+y

array([[ 2,  4],
       [ 4,  6],
       [ 6,  8],
       [ 8, 10]])

In [64]:
arr=np.array([1,2,1010,4,8,181,7,100])
arr

array([   1,    2, 1010,    4,    8,  181,    7,  100])

In [66]:
arr<100

array([ True,  True, False,  True,  True, False,  True, False])

In [67]:
# where
np.where(arr>100)

(array([2, 5]),)

In [68]:
np.where(arr==100)

(array([7]),)

In [69]:
arr[arr>100]

array([1010,  181])

In [72]:
# copy
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [74]:
arr2 = arr1
arr2

array([1, 2, 3, 4, 5])

In [75]:
arr2[1]=9
arr2

array([1, 9, 3, 4, 5])

In [76]:
arr1

array([1, 9, 3, 4, 5])

In [77]:
arr3 = arr1.copy()

In [78]:
arr3

array([1, 9, 3, 4, 5])

In [79]:
arr3[3:]=10
arr3

array([ 1,  9,  3, 10, 10])

In [80]:
arr1

array([1, 9, 3, 4, 5])

# Indexing

In [81]:
arr = np.array([3,4,5,6,7,8,9,10])
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr[3:6]

array([6, 7, 8])

In [83]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [84]:
arr_2d[2][0]

35

In [85]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [86]:
arr_2d[1][0]

20

In [87]:
arr_2d[1,0]

20

In [88]:
arr_2d[0:2][0]

array([ 5, 10, 15])

In [89]:
arr_2d[2,:]

array([35, 40, 45])

In [91]:
ary=np.array([[1,2,3],[4,5,6],[6,7,8]])
ary

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [93]:
ary.ndim

2

In [96]:
ary.reshape(9, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [6],
       [7],
       [8]])

In [97]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
np.add.reduce(x, 1)

array([ 3, 12, 21])

In [99]:
np.add.reduce(x, 0)

array([ 9, 12, 15])

In [101]:
np.multiply.reduce(x, 1, dtype=float)

array([  0.,  60., 336.])

# Pandas

In [102]:
import pandas as pd
import numpy as np

In [103]:
d=pd.Series()
d

Series([], dtype: float64)

In [104]:
type(d)

pandas.core.series.Series

In [105]:
t=(10,20,30,40,50)
d=pd.Series(t)
d

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [106]:
arr=np.array([1,2,3,4,5,6])
ser=pd.Series(arr)
ser

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [107]:
d={'a':1,'b':2,'c':3,'d':4}
b=pd.Series(d)
b

a    1
b    2
c    3
d    4
dtype: int64

In [108]:
b[0]

1

In [109]:
b['c']

3

In [110]:
# Slicing operation
d=pd.Series([1,2,3,5,47,98,7,8,6,32,78,2,8,289,258,78])
d

0       1
1       2
2       3
3       5
4      47
5      98
6       7
7       8
8       6
9      32
10     78
11      2
12      8
13    289
14    258
15     78
dtype: int64

In [111]:
d[0:4]

0    1
1    2
2    3
3    5
dtype: int64

In [112]:
d[[4,5,3,6]]

4    47
5    98
3     5
6     7
dtype: int64

In [113]:
d[0]=10
d

0      10
1       2
2       3
3       5
4      47
5      98
6       7
7       8
8       6
9      32
10     78
11      2
12      8
13    289
14    258
15     78
dtype: int64

In [114]:
s=pd.Series(arr,index=['a','b','c','d','e','f'])
s

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

# Dataframe

In [117]:
data=[[1,2,3,'b'],[14,12,1,'j',8],[7,8,9, 'k'], [34, 56, 2, 3, 3]]
data

[[1, 2, 3, 'b'], [14, 12, 1, 'j', 8], [7, 8, 9, 'k'], [34, 56, 2, 3, 3]]

In [119]:
data1=pd.DataFrame(data)
data1

0   1  2  3    4
0   1   2  3  b  NaN
1  14  12  1  j  8.0
2   7   8  9  k  NaN
3  34  56  2  3  3.0

In [120]:
data2=(('abc',1),('def',2),('ghi',3),('hij',8),('lmn',5))
df=pd.DataFrame(data2,index=['A','B','C','D','E'],columns=['Name','Number'])
df

Name  Number
A  abc       1
B  def       2
C  ghi       3
D  hij       8
E  lmn       5

In [125]:
df.rename({'Name':'Person','Number':'No'}, axis=1, inplace=True)

In [126]:
df

Person  No
A    abc   1
B    def   2
C    ghi   3
D    hij   8
E    lmn   5

In [127]:
df.rename({'Person':'co1','No':'co2'}, axis=1)

co1  co2
A  abc    1
B  def    2
C  ghi    3
D  hij    8
E  lmn    5

In [128]:
d.rename({1:'b'}, axis=0)

0      10
b       2
2       3
3       5
4      47
5      98
6       7
7       8
8       6
9      32
10     78
11      2
12      8
13    289
14    258
15     78
dtype: int64

# loc & iloc

In [129]:
df

Person  No
A    abc   1
B    def   2
C    ghi   3
D    hij   8
E    lmn   5

In [130]:
data=[['Alex',10,'Maths'],['Bob',12,'Science'],['Kelly',15,'Eco'],['Boris',14,'Geo'],['Ken',18,'English']]

In [131]:
d=pd.DataFrame(data,columns=['Name','Age','Subject'])
d

Name  Age  Subject
0   Alex   10    Maths
1    Bob   12  Science
2  Kelly   15      Eco
3  Boris   14      Geo
4    Ken   18  English

In [132]:
d.iloc[1:3,[0, 1]]

Name  Age
1    Bob   12
2  Kelly   15

In [134]:
d.loc[1:3, ['Name','Subject']]

Name  Subject
1    Bob  Science
2  Kelly      Eco
3  Boris      Geo

In [135]:
d.loc[1:3,['Age','Subject']]

Age  Subject
1   12  Science
2   15      Eco
3   14      Geo

In [136]:
d.iloc[[0,2,1],[0,1]]

Name  Age
0   Alex   10
2  Kelly   15
1    Bob   12

In [138]:
dat = pd.read_csv('ABC.csv')
dat

Unnamed: 0    Eastern Conference                   W                   L  \
0            0     Atlantic Division   Atlantic Division   Atlantic Division   
1            1      Toronto Raptors*                  49                  33   
2            2       Boston Celtics*                  40                  42   
3            3        Brooklyn Nets*                  38                  44   
4            4    Philadelphia 76ers                  18                  64   
5            5       New York Knicks                  17                  65   
6            6      Central Division    Central Division    Central Division   
7            7  Cleveland Cavaliers*                  53                  29   
8            8        Chicago Bulls*                  50                  32   
9            9      Milwaukee Bucks*                  41                  41   
10          10        Indiana Pacers                  38                  44   
11          11       Detroit Pistons                  32                  50   
12          12    Southeast Division  Southeast Division  Southeast Division   
13          13        Atlanta Hawks*                  60                  22   
14          14   Washington Wizards*                  46                  36   
15          15            Miami Heat                  37                  45   
16          16     Charlotte Hornets                  33                  49   
17          17         Orlando Magic                  25                  57   

                  W/L%                  GB                PS/G  \
0    Atlantic Division   Atlantic Division   Atlantic Division   
1                 .598                   —               104.0   
2                 .488                 9.0               101.4   
3                 .463                11.0                98.0   
4                 .220                31.0                92.0   
5                 .207                32.0                91.9   
6     Central Division    Central Division    Central Division   
7                 .646                   —               103.1   
8                 .610                 3.0               100.8   
9                 .500                12.0                97.8   
10                .463                15.0                97.3   
11                .390                21.0                98.5   
12  Southeast Division  Southeast Division  Southeast Division   
13                .732                   —               102.5   
14                .561                14.0                98.5   
15                .451                23.0                94.7   
16                .402                27.0                94.2   
17                .305                35.0                95.7   

                  PA/G                 SRS  
0    Atlantic Division   Atlantic Division  
1                100.9                2.45  
2                101.2               -0.40  
3                100.9               -3.13  
4                101.0               -9.04  
5                101.2               -9.50  
6     Central Division    Central Division  
7                 98.7                4.08  
8                 97.8                2.54  
9                 97.4               -0.09  
10                97.0               -0.23  
11                99.5               -1.39  
12  Southeast Division  Southeast Division  
13                97.1                4.75  
14                97.8                0.17  
15                97.3               -2.92  
16                97.3               -3.44  
17               101.4               -5.87

In [139]:
pd.set_option('display.max_rows',None)
dat

Unnamed: 0    Eastern Conference                   W                   L  \
0            0     Atlantic Division   Atlantic Division   Atlantic Division   
1            1      Toronto Raptors*                  49                  33   
2            2       Boston Celtics*                  40                  42   
3            3        Brooklyn Nets*                  38                  44   
4            4    Philadelphia 76ers                  18                  64   
5            5       New York Knicks                  17                  65   
6            6      Central Division    Central Division    Central Division   
7            7  Cleveland Cavaliers*                  53                  29   
8            8        Chicago Bulls*                  50                  32   
9            9      Milwaukee Bucks*                  41                  41   
10          10        Indiana Pacers                  38                  44   
11          11       Detroit Pistons                  32                  50   
12          12    Southeast Division  Southeast Division  Southeast Division   
13          13        Atlanta Hawks*                  60                  22   
14          14   Washington Wizards*                  46                  36   
15          15            Miami Heat                  37                  45   
16          16     Charlotte Hornets                  33                  49   
17          17         Orlando Magic                  25                  57   

                  W/L%                  GB                PS/G  \
0    Atlantic Division   Atlantic Division   Atlantic Division   
1                 .598                   —               104.0   
2                 .488                 9.0               101.4   
3                 .463                11.0                98.0   
4                 .220                31.0                92.0   
5                 .207                32.0                91.9   
6     Central Division    Central Division    Central Division   
7                 .646                   —               103.1   
8                 .610                 3.0               100.8   
9                 .500                12.0                97.8   
10                .463                15.0                97.3   
11                .390                21.0                98.5   
12  Southeast Division  Southeast Division  Southeast Division   
13                .732                   —               102.5   
14                .561                14.0                98.5   
15                .451                23.0                94.7   
16                .402                27.0                94.2   
17                .305                35.0                95.7   

                  PA/G                 SRS  
0    Atlantic Division   Atlantic Division  
1                100.9                2.45  
2                101.2               -0.40  
3                100.9               -3.13  
4                101.0               -9.04  
5                101.2               -9.50  
6     Central Division    Central Division  
7                 98.7                4.08  
8                 97.8                2.54  
9                 97.4               -0.09  
10                97.0               -0.23  
11                99.5               -1.39  
12  Southeast Division  Southeast Division  
13                97.1                4.75  
14                97.8                0.17  
15                97.3               -2.92  
16                97.3               -3.44  
17               101.4               -5.87

In [140]:
pd.reset_option('display.max_rows',None)
dat

Unnamed: 0    Eastern Conference                   W                   L  \
0            0     Atlantic Division   Atlantic Division   Atlantic Division   
1            1      Toronto Raptors*                  49                  33   
2            2       Boston Celtics*                  40                  42   
3            3        Brooklyn Nets*                  38                  44   
4            4    Philadelphia 76ers                  18                  64   
5            5       New York Knicks                  17                  65   
6            6      Central Division    Central Division    Central Division   
7            7  Cleveland Cavaliers*                  53                  29   
8            8        Chicago Bulls*                  50                  32   
9            9      Milwaukee Bucks*                  41                  41   
10          10        Indiana Pacers                  38                  44   
11          11       Detroit Pistons                  32                  50   
12          12    Southeast Division  Southeast Division  Southeast Division   
13          13        Atlanta Hawks*                  60                  22   
14          14   Washington Wizards*                  46                  36   
15          15            Miami Heat                  37                  45   
16          16     Charlotte Hornets                  33                  49   
17          17         Orlando Magic                  25                  57   

                  W/L%                  GB                PS/G  \
0    Atlantic Division   Atlantic Division   Atlantic Division   
1                 .598                   —               104.0   
2                 .488                 9.0               101.4   
3                 .463                11.0                98.0   
4                 .220                31.0                92.0   
5                 .207                32.0                91.9   
6     Central Division    Central Division    Central Division   
7                 .646                   —               103.1   
8                 .610                 3.0               100.8   
9                 .500                12.0                97.8   
10                .463                15.0                97.3   
11                .390                21.0                98.5   
12  Southeast Division  Southeast Division  Southeast Division   
13                .732                   —               102.5   
14                .561                14.0                98.5   
15                .451                23.0                94.7   
16                .402                27.0                94.2   
17                .305                35.0                95.7   

                  PA/G                 SRS  
0    Atlantic Division   Atlantic Division  
1                100.9                2.45  
2                101.2               -0.40  
3                100.9               -3.13  
4                101.0               -9.04  
5                101.2               -9.50  
6     Central Division    Central Division  
7                 98.7                4.08  
8                 97.8                2.54  
9                 97.4               -0.09  
10                97.0               -0.23  
11                99.5               -1.39  
12  Southeast Division  Southeast Division  
13                97.1                4.75  
14                97.8                0.17  
15                97.3               -2.92  
16                97.3               -3.44  
17               101.4               -5.87

In [142]:
dat.head()

Unnamed: 0  Eastern Conference                  W                  L  \
0           0   Atlantic Division  Atlantic Division  Atlantic Division   
1           1    Toronto Raptors*                 49                 33   
2           2     Boston Celtics*                 40                 42   
3           3      Brooklyn Nets*                 38                 44   
4           4  Philadelphia 76ers                 18                 64   

                W/L%                 GB               PS/G               PA/G  \
0  Atlantic Division  Atlantic Division  Atlantic Division  Atlantic Division   
1               .598                  —              104.0              100.9   
2               .488                9.0              101.4              101.2   
3               .463               11.0               98.0              100.9   
4               .220               31.0               92.0              101.0   

                 SRS  
0  Atlantic Division  
1               2.45  
2              -0.40  
3              -3.13  
4              -9.04

In [143]:
dat.tail()

Unnamed: 0   Eastern Conference   W   L  W/L%    GB   PS/G   PA/G    SRS
13          13       Atlanta Hawks*  60  22  .732     —  102.5   97.1   4.75
14          14  Washington Wizards*  46  36  .561  14.0   98.5   97.8   0.17
15          15           Miami Heat  37  45  .451  23.0   94.7   97.3  -2.92
16          16    Charlotte Hornets  33  49  .402  27.0   94.2   97.3  -3.44
17          17        Orlando Magic  25  57  .305  35.0   95.7  101.4  -5.87

In [144]:
dat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Unnamed: 0          18 non-null     int64 
 1   Eastern Conference  18 non-null     object
 2   W                   18 non-null     object
 3   L                   18 non-null     object
 4   W/L%                18 non-null     object
 5   GB                  18 non-null     object
 6   PS/G                18 non-null     object
 7   PA/G                18 non-null     object
 8   SRS                 18 non-null     object
dtypes: int64(1), object(8)
memory usage: 1.4+ KB


In [145]:
dat.describe(include='O')

Eastern Conference   W   L  W/L%  GB  PS/G   PA/G                SRS
count                  18  18  18    18  18    18     18                 18
unique                 18  17  17    17  16    17     14                 18
top     Atlantic Division  38  44  .463   —  98.5  100.9  Atlantic Division
freq                    1   2   2     2   3     2      2                  1

In [146]:
dat.columns

Index(['Unnamed: 0', 'Eastern Conference', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS'],
      dtype='object')

In [149]:
dat.W.unique()

array(['Atlantic Division', '49', '40', '38', '18', '17',
       'Central Division', '53', '50', '41', '32', 'Southeast Division',
       '60', '46', '37', '33', '25'], dtype=object)

In [150]:
dat.GB.unique()

array(['Atlantic Division', '—', '9.0', '11.0', '31.0', '32.0',
       'Central Division', '3.0', '12.0', '15.0', '21.0',
       'Southeast Division', '14.0', '23.0', '27.0', '35.0'], dtype=object)

In [151]:
dat[['W','GB']]

W                  GB
0    Atlantic Division   Atlantic Division
1                   49                   —
2                   40                 9.0
3                   38                11.0
4                   18                31.0
5                   17                32.0
6     Central Division    Central Division
7                   53                   —
8                   50                 3.0
9                   41                12.0
10                  38                15.0
11                  32                21.0
12  Southeast Division  Southeast Division
13                  60                   —
14                  46                14.0
15                  37                23.0
16                  33                27.0
17                  25                35.0

In [152]:
dat.iloc[1:6,[0,1]]

Unnamed: 0  Eastern Conference
1           1    Toronto Raptors*
2           2     Boston Celtics*
3           3      Brooklyn Nets*
4           4  Philadelphia 76ers
5           5     New York Knicks

In [154]:
dat.loc[1:6, ['W','L','GB']]

W                 L                GB
1                49                33                 —
2                40                42               9.0
3                38                44              11.0
4                18                64              31.0
5                17                65              32.0
6  Central Division  Central Division  Central Division